"""Tables and figures from results/runs.csv.

    python -m fairmatch.report
"""

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import pandas as pd  # noqa: E402
import yaml  # noqa: E402

METRICS = [
    ("ndcg_true", "NDCG@10 vs true suitability"),
    ("ndcg_hist", "NDCG@10 vs past shortlists"),
    ("eo_ratio", "Equal opportunity ratio"),
    ("selection_ratio", "Selection ratio"),
    ("exposure_ratio", "Exposure ratio"),
]
ORDER = ["oracle", "historical", "baseline", "unaware", "rerank", "penalty"]


def mean_std(frame, by):
    cols = [m for m, _ in METRICS]
    agg = frame.groupby(by, observed=True)[cols].agg(["mean", "std"])
    return agg


def md_table(agg, index_label):
    head = f"| {index_label} | " + " | ".join(label for _, label in METRICS) + " |"
    sep = "|---" * (len(METRICS) + 1) + "|"
    lines = [head, sep]
    for idx, row in agg.iterrows():
        name = " / ".join(str(i) for i in idx) if isinstance(idx, tuple) else str(idx)
        cells = [f"{row[(m, 'mean')]:.3f} ± {row[(m, 'std')]:.3f}" for m, _ in METRICS]
        lines.append(f"| {name} | " + " | ".join(cells) + " |")
    return "\n".join(lines)


def build(runs, cfg):
    out = Path(cfg["output_dir"])
    fig_dir = out / "figures"
    fig_dir.mkdir(parents=True, exist_ok=True)
    main_bias = cfg["history"]["bias"]
    sweep_lam = cfg["fairness"]["sweep_lambda"]
    main = runs[runs["bias"] == main_bias]

    # main comparison: every variant, penalty at the sweep lambda
    comp = main[(main["variant"] != "penalty") | (main["lambda"] == sweep_lam)].copy()
    comp["variant"] = pd.Categorical(comp["variant"], ORDER, ordered=True)
    comp_agg = mean_std(comp, "variant").loc[lambda d: d.index.isin(comp["variant"].unique())]

    lam = main[main["variant"].isin(["unaware", "penalty"])].copy()
    lam.loc[lam["variant"] == "unaware", "lambda"] = 0.0
    lam_agg = mean_std(lam, "lambda")

    sweep = runs[runs["variant"].isin(["historical", "baseline", "unaware", "rerank"]) |
                 ((runs["variant"] == "penalty") & (runs["lambda"] == sweep_lam))]
    sweep_agg = mean_std(sweep, ["bias", "variant"])

    n_seeds = runs["seed"].nunique()
    text = [
        "# Results",
        "",
        f"Generated by `python -m fairmatch.report`. Mean ± standard deviation over {n_seeds} seeds; "
        f"each seed is a new synthetic market and a new model. Ratios compare group B "
        f"(internationally trained) with group A; 1.0 means parity.",
        "",
        f"## Main comparison (bias = {main_bias}, penalty lambda = {sweep_lam})",
        "",
        md_table(comp_agg, "Variant"),
        "",
        "## Fairness penalty sweep",
        "",
        md_table(lam_agg, "lambda"),
        "",
        "## Bias sweep",
        "",
        md_table(sweep_agg, "bias / variant"),
        "",
    ]
    (out / "RESULTS.md").write_text("\n".join(text), encoding="utf-8")

    # figure 1: accuracy vs fairness for each variant
    fig, ax = plt.subplots(figsize=(6, 4.5))
    for variant, row in comp_agg.iterrows():
        ax.errorbar(row[("eo_ratio", "mean")], row[("ndcg_true", "mean")],
                    xerr=row[("eo_ratio", "std")], yerr=row[("ndcg_true", "std")], fmt="o", capsize=3)
        ax.annotate(str(variant), (row[("eo_ratio", "mean")], row[("ndcg_true", "mean")]),
                    textcoords="offset points", xytext=(6, 4), fontsize=9)
    ax.axvline(1.0, ls="--", color="grey", lw=1)
    ax.set_xlabel("Equal opportunity ratio (group B / group A)")
    ax.set_ylabel("NDCG@10 vs true suitability")
    ax.set_title("Ranking quality against fairness")
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(fig_dir / "quality_vs_fairness.png", dpi=150)
    plt.close(fig)

    # figure 2: lambda sweep
    fig, ax1 = plt.subplots(figsize=(6, 4))
    x = lam_agg.index.to_numpy()
    xs = range(len(x))
    ax1.errorbar(xs, lam_agg[("ndcg_true", "mean")], lam_agg[("ndcg_true", "std")], marker="o", label="NDCG@10 (true)")
    ax1.errorbar(xs, lam_agg[("ndcg_hist", "mean")], lam_agg[("ndcg_hist", "std")], marker="s", label="NDCG@10 (past shortlists)")
    ax1.set_ylabel("NDCG@10")
    ax2 = ax1.twinx()
    ax2.errorbar(xs, lam_agg[("eo_ratio", "mean")], lam_agg[("eo_ratio", "std")], marker="^", color="tab:red", label="EO ratio")
    ax2.set_ylabel("Equal opportunity ratio", color="tab:red")
    ax1.set_xticks(list(xs), [f"{v:g}" for v in x])
    ax1.set_xlabel("Fairness penalty lambda")
    lines = ax1.get_legend_handles_labels()[0] + ax2.get_legend_handles_labels()[0]
    ax1.legend(lines, [h.get_label() for h in lines], loc="lower left", fontsize=8)
    ax1.set_title("Effect of the fairness penalty")
    ax1.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(fig_dir / "lambda_sweep.png", dpi=150)
    plt.close(fig)

    # figure 3: how each variant responds to the strength of historical bias
    fig, ax = plt.subplots(figsize=(6, 4))
    for variant in ["historical", "baseline", "unaware", "rerank", "penalty"]:
        if variant not in sweep_agg.index.get_level_values("variant"):
            continue
        d = sweep_agg.xs(variant, level="variant")
        ax.errorbar(d.index, d[("eo_ratio", "mean")], d[("eo_ratio", "std")], marker="o", capsize=3, label=variant)
    ax.axhline(1.0, ls="--", color="grey", lw=1)
    ax.set_xlabel("Bias against group B in past shortlists")
    ax.set_ylabel("Equal opportunity ratio")
    ax.set_title("What each model learns from biased history")
    ax.grid(alpha=0.3)
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(fig_dir / "bias_sweep.png", dpi=150)
    plt.close(fig)

    print(f"wrote {out / 'RESULTS.md'} and {fig_dir}/")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config", default="config.yaml")
    args = ap.parse_args()
    cfg = yaml.safe_load(Path(args.config).read_text(encoding="utf-8"))
    build(pd.read_csv(Path(cfg["output_dir"]) / "runs.csv"), cfg)


if __name__ == "__main__":
    main()
